// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.3
// source: pkg/proto/notification.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConfirmRegistrationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Code  string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *ConfirmRegistrationRequest) Reset() {
	*x = ConfirmRegistrationRequest{}
	mi := &file_pkg_proto_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmRegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmRegistrationRequest) ProtoMessage() {}

func (x *ConfirmRegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmRegistrationRequest.ProtoReflect.Descriptor instead.
func (*ConfirmRegistrationRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_notification_proto_rawDescGZIP(), []int{0}
}

func (x *ConfirmRegistrationRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ConfirmRegistrationRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

var File_pkg_proto_notification_proto protoreflect.FileDescriptor

var file_pkg_proto_notification_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6e, 0x6f, 0x74, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02,
	0x70, 0x62, 0x22, 0x46, 0x0a, 0x1a, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x42, 0x0e, 0x5a, 0x0c, 0x70, 0x6b,
	0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_pkg_proto_notification_proto_rawDescOnce sync.Once
	file_pkg_proto_notification_proto_rawDescData = file_pkg_proto_notification_proto_rawDesc
)

func file_pkg_proto_notification_proto_rawDescGZIP() []byte {
	file_pkg_proto_notification_proto_rawDescOnce.Do(func() {
		file_pkg_proto_notification_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_proto_notification_proto_rawDescData)
	})
	return file_pkg_proto_notification_proto_rawDescData
}

var file_pkg_proto_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_proto_notification_proto_goTypes = []any{
	(*ConfirmRegistrationRequest)(nil), // 0: pb.ConfirmRegistrationRequest
}
var file_pkg_proto_notification_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_proto_notification_proto_init() }
func file_pkg_proto_notification_proto_init() {
	if File_pkg_proto_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_proto_notification_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_proto_notification_proto_goTypes,
		DependencyIndexes: file_pkg_proto_notification_proto_depIdxs,
		MessageInfos:      file_pkg_proto_notification_proto_msgTypes,
	}.Build()
	File_pkg_proto_notification_proto = out.File
	file_pkg_proto_notification_proto_rawDesc = nil
	file_pkg_proto_notification_proto_goTypes = nil
	file_pkg_proto_notification_proto_depIdxs = nil
}
